/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.donacionAlimentos.view;

import com.donacionAlimentos.view.components.PLabelButton;
import java.awt.CardLayout;

/**
 * clase manejadora de la navegacion
 *
 * @author erwbyel
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        setTitle("Sistema Donaciones");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setResizable(false);
        setSize(860, 600);
        pnlContenido.setLayout(new CardLayout());
        pnlContenido.add(new pnlInicio(), "inicio");
        //personas
        pnlContenido.add(new pnlPersonas(), "personas");
        pnlContenido.add(new pnlDonantes(), "donadores");
        pnlContenido.add(new pnlOrganizaciones(), "organizaciones");
        //objetos
        pnlContenido.add(new pnlAlimentos(), "alimentos");
        pnlContenido.add(new pnlAportaciones(), "aportaciones");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pnlNavegacion = new javax.swing.JPanel();
        btnInicio = new javax.swing.JLabel();
        btnPersonas = new PLabelButton();
        btnDonadores = new PLabelButton();
        btnOrganizaciones = new PLabelButton();
        btnAlimentos = new PLabelButton();
        btnAportaciones = new PLabelButton();
        pnlContenido = new javax.swing.JPanel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlNavegacion.setBackground(new java.awt.Color(23, 17, 55));
        pnlNavegacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnInicio.setBackground(new java.awt.Color(255, 255, 255));
        btnInicio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons/inicio-icon.png"))); // NOI18N
        btnInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInicioMouseClicked(evt);
            }
        });
        pnlNavegacion.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        btnPersonas.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        btnPersonas.setForeground(new java.awt.Color(255, 255, 255));
        btnPersonas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnPersonas.setText("Personas");
        btnPersonas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPersonas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPersonasMouseClicked(evt);
            }
        });
        pnlNavegacion.add(btnPersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 0, 100, 50));

        btnDonadores.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        btnDonadores.setForeground(new java.awt.Color(255, 255, 255));
        btnDonadores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDonadores.setText("Donantes");
        btnDonadores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDonadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDonadoresMouseClicked(evt);
            }
        });
        pnlNavegacion.add(btnDonadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 100, 50));

        btnOrganizaciones.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        btnOrganizaciones.setForeground(new java.awt.Color(255, 255, 255));
        btnOrganizaciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnOrganizaciones.setText("Organizaciones");
        btnOrganizaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOrganizaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOrganizacionesMouseClicked(evt);
            }
        });
        pnlNavegacion.add(btnOrganizaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 150, 50));

        btnAlimentos.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        btnAlimentos.setForeground(new java.awt.Color(255, 255, 255));
        btnAlimentos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAlimentos.setText("Alimentos");
        btnAlimentos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlimentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAlimentosMouseClicked(evt);
            }
        });
        pnlNavegacion.add(btnAlimentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 100, 50));

        btnAportaciones.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        btnAportaciones.setForeground(new java.awt.Color(255, 255, 255));
        btnAportaciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAportaciones.setText("Aportaciones");
        btnAportaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAportaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAportacionesMouseClicked(evt);
            }
        });
        pnlNavegacion.add(btnAportaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 110, 50));

        getContentPane().add(pnlNavegacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 50));

        pnlContenido.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlContenidoLayout = new javax.swing.GroupLayout(pnlContenido);
        pnlContenido.setLayout(pnlContenidoLayout);
        pnlContenidoLayout.setHorizontalGroup(
            pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );
        pnlContenidoLayout.setVerticalGroup(
            pnlContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        getContentPane().add(pnlContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 860, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMouseClicked
        CardLayout cl = (CardLayout) pnlContenido.getLayout();
        cl.show(pnlContenido, "inicio");
    }//GEN-LAST:event_btnInicioMouseClicked

    private void btnOrganizacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOrganizacionesMouseClicked
        CardLayout cl = (CardLayout) pnlContenido.getLayout();
        cl.show(pnlContenido, "organizaciones");
    }//GEN-LAST:event_btnOrganizacionesMouseClicked

    private void btnAlimentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlimentosMouseClicked
        CardLayout cl = (CardLayout) pnlContenido.getLayout();
        cl.show(pnlContenido, "alimentos");
    }//GEN-LAST:event_btnAlimentosMouseClicked

    private void btnAportacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAportacionesMouseClicked
        CardLayout cl = (CardLayout) pnlContenido.getLayout();
        cl.show(pnlContenido, "aportaciones");
    }//GEN-LAST:event_btnAportacionesMouseClicked

    private void btnDonadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDonadoresMouseClicked
        CardLayout cl = (CardLayout) pnlContenido.getLayout();
        cl.show(pnlContenido, "donadores");
    }//GEN-LAST:event_btnDonadoresMouseClicked

    private void btnPersonasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPersonasMouseClicked
        CardLayout cl = (CardLayout) pnlContenido.getLayout();
        cl.show(pnlContenido, "personas");
    }//GEN-LAST:event_btnPersonasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAlimentos;
    private javax.swing.JLabel btnAportaciones;
    private javax.swing.JLabel btnDonadores;
    private javax.swing.JLabel btnInicio;
    private javax.swing.JLabel btnOrganizaciones;
    private javax.swing.JLabel btnPersonas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnlContenido;
    private javax.swing.JPanel pnlNavegacion;
    // End of variables declaration//GEN-END:variables
}
