/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.donacionAlimentos.view;

import java.awt.BorderLayout;
import javax.swing.JFrame;

/**
 *
 * @author saidr
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
    }
    private void mostrarEnPanel(JFrame frame) {
    panelContenido.removeAll();             // limpiar panel
    panelContenido.setLayout(new BorderLayout()); // definir layout
    panelContenido.add(frame.getContentPane(), BorderLayout.CENTER); // agregar contenido
    panelContenido.revalidate();            // refrescar panel
    panelContenido.repaint();               // repintar
    frame.pack();                           // ajustar tamaño
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem5 = new javax.swing.JMenuItem();
        panelContenido = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuBar = new javax.swing.JMenu();
        donante = new javax.swing.JMenuItem();
        aportaciones = new javax.swing.JMenuItem();
        alimentos = new javax.swing.JMenuItem();
        entregas = new javax.swing.JMenuItem();
        contenido = new javax.swing.JMenuItem();
        personas = new javax.swing.JMenuItem();
        organizacion = new javax.swing.JMenuItem();

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelContenidoLayout = new javax.swing.GroupLayout(panelContenido);
        panelContenido.setLayout(panelContenidoLayout);
        panelContenidoLayout.setHorizontalGroup(
            panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 789, Short.MAX_VALUE)
        );
        panelContenidoLayout.setVerticalGroup(
            panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
        );

        menuBar.setText("MENU");

        donante.setText("Donante");
        donante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donanteActionPerformed(evt);
            }
        });
        menuBar.add(donante);

        aportaciones.setText("Aportaciones");
        aportaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aportacionesActionPerformed(evt);
            }
        });
        menuBar.add(aportaciones);

        alimentos.setText("Alimento");
        alimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alimentosActionPerformed(evt);
            }
        });
        menuBar.add(alimentos);

        entregas.setText("Entregas");
        entregas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entregasActionPerformed(evt);
            }
        });
        menuBar.add(entregas);

        contenido.setText("Contenido");
        contenido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contenidoActionPerformed(evt);
            }
        });
        menuBar.add(contenido);

        personas.setText("Personas");
        personas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personasActionPerformed(evt);
            }
        });
        menuBar.add(personas);

        organizacion.setText("Organizacion");
        organizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizacionActionPerformed(evt);
            }
        });
        menuBar.add(organizacion);

        jMenuBar1.add(menuBar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void donanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donanteActionPerformed
        // TODO add your handling code here:
            FrmDonante frm = new FrmDonante();
    mostrarEnPanel(frm);
    }//GEN-LAST:event_donanteActionPerformed

    private void alimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alimentosActionPerformed
        // TODO add your handling code here:
            FrmAlimento frm = new FrmAlimento();
    mostrarEnPanel(frm);
    }//GEN-LAST:event_alimentosActionPerformed

    private void organizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizacionActionPerformed
        // TODO add your handling code here
            FrmOrganizacion frm = new FrmOrganizacion();
    mostrarEnPanel(frm);
    }//GEN-LAST:event_organizacionActionPerformed

    private void entregasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entregasActionPerformed
        // TODO add your handling code here
       FrmEntrega frm = new FrmEntrega();
    mostrarEnPanel(frm);
    }//GEN-LAST:event_entregasActionPerformed

    private void contenidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contenidoActionPerformed
        // TODO add your handling code here:
         FrmContenido frm = new FrmContenido();
    mostrarEnPanel(frm);
    }//GEN-LAST:event_contenidoActionPerformed

    private void personasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personasActionPerformed
        // TODO add your handling code here:
            FrmPersona frm = new FrmPersona();
    mostrarEnPanel(frm);
    }//GEN-LAST:event_personasActionPerformed

    private void aportacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aportacionesActionPerformed
        // TODO add your handling code here:
        FrmAportacion frm = new FrmAportacion();
        mostrarEnPanel(frm);
    }//GEN-LAST:event_aportacionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem alimentos;
    private javax.swing.JMenuItem aportaciones;
    private javax.swing.JMenuItem contenido;
    private javax.swing.JMenuItem donante;
    private javax.swing.JMenuItem entregas;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenu menuBar;
    private javax.swing.JMenuItem organizacion;
    private javax.swing.JPanel panelContenido;
    private javax.swing.JMenuItem personas;
    // End of variables declaration//GEN-END:variables
}
