package com.donacionAlimentos.view;

import com.donacionAlimentos.controllers.AlimentoController;
import com.donacionAlimentos.view.components.DlgBuscarPersonas;
import com.donacionAlimentos.view.components.PLabelButton;
import java.awt.HeadlessException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 * clase tipo panel que permite gestionar visualmente a los donadores
 *
 * @author erwbyel
 */
public class pnlAlimentos extends javax.swing.JPanel {
     
    private AlimentoController almController;

    /**
     * Creates new form pnlDonantes
     */
    public pnlAlimentos() {
        initComponents();
        almController = new AlimentoController();
        cargarAlimentos();
        btnLimpieza.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDatosPersonales = new com.donacionAlimentos.view.components.PanelRound();
        lblTituloDP = new javax.swing.JLabel();
        pnlId = new javax.swing.JPanel();
        txtId = new javax.swing.JTextField();
        lblId = new javax.swing.JLabel();
        pnlNombre = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        pnlCantidad = new javax.swing.JPanel();
        txtCantidad = new javax.swing.JTextField();
        lblCantidad = new javax.swing.JLabel();
        pnlTipo = new javax.swing.JPanel();
        txtTipo = new javax.swing.JTextField();
        lblTipo = new javax.swing.JLabel();
        pnlBotones = new javax.swing.JPanel();
        btnDonar = new com.donacionAlimentos.view.components.PanelRound();
        lblDonar = new PLabelButton();
        btnCancelar = new com.donacionAlimentos.view.components.PanelRound();
        lblCancelar = new PLabelButton();
        btnLimpieza = new com.donacionAlimentos.view.components.PanelRound();
        lblLimpieza = new PLabelButton();
        scrlPaneAlimentos = new javax.swing.JScrollPane();
        tblAlimentos = new javax.swing.JTable();
        txtBuscar = new javax.swing.JTextField();

        setBackground(new java.awt.Color(37, 37, 64));
        setPreferredSize(new java.awt.Dimension(860, 441));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlDatosPersonales.setBackground(new java.awt.Color(23, 17, 55));
        pnlDatosPersonales.setRoundBottomRight(30);
        pnlDatosPersonales.setRoundTopRight(30);
        pnlDatosPersonales.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloDP.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        lblTituloDP.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloDP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloDP.setText("Informacion Alimento");
        pnlDatosPersonales.add(lblTituloDP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 360, -1));

        pnlId.setOpaque(false);
        pnlId.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtId.setEditable(false);
        txtId.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        txtId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtId.setBorder(null);
        txtId.setFocusable(false);
        pnlId.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 5, 40, 30));

        lblId.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        lblId.setForeground(new java.awt.Color(255, 255, 255));
        lblId.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblId.setText("ID");
        pnlId.add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        pnlDatosPersonales.add(pnlId, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 300, 40));

        pnlNombre.setOpaque(false);
        pnlNombre.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombre.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        txtNombre.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNombre.setBorder(null);
        pnlNombre.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 5, 200, 30));

        lblNombre.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNombre.setText("Nombre");
        pnlNombre.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 40));

        pnlDatosPersonales.add(pnlNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 300, 40));

        pnlCantidad.setOpaque(false);
        pnlCantidad.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCantidad.setEditable(false);
        txtCantidad.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        txtCantidad.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtCantidad.setBorder(null);
        pnlCantidad.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 5, 200, 30));

        lblCantidad.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        lblCantidad.setForeground(new java.awt.Color(255, 255, 255));
        lblCantidad.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCantidad.setText("Cantidad");
        pnlCantidad.add(lblCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 40));

        pnlDatosPersonales.add(pnlCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 300, 40));

        pnlTipo.setOpaque(false);
        pnlTipo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTipo.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        txtTipo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTipo.setBorder(null);
        pnlTipo.add(txtTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 5, 200, 30));

        lblTipo.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        lblTipo.setForeground(new java.awt.Color(255, 255, 255));
        lblTipo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTipo.setText("Tipo");
        pnlTipo.add(lblTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 40));

        pnlDatosPersonales.add(pnlTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 300, 40));

        add(pnlDatosPersonales, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 370, 200));

        pnlBotones.setOpaque(false);
        pnlBotones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDonar.setBackground(new java.awt.Color(0, 102, 0));
        btnDonar.setRoundBottomLeft(20);
        btnDonar.setRoundBottomRight(20);
        btnDonar.setRoundTopLeft(20);
        btnDonar.setRoundTopRight(20);
        btnDonar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDonar.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        lblDonar.setForeground(new java.awt.Color(255, 255, 255));
        lblDonar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDonar.setText("DONAR");
        lblDonar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblDonar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDonarMouseClicked(evt);
            }
        });
        btnDonar.add(lblDonar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 30));

        pnlBotones.add(btnDonar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 140, 30));

        btnCancelar.setBackground(new java.awt.Color(0, 51, 153));
        btnCancelar.setRoundBottomLeft(20);
        btnCancelar.setRoundBottomRight(20);
        btnCancelar.setRoundTopLeft(20);
        btnCancelar.setRoundTopRight(20);
        btnCancelar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCancelar.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        lblCancelar.setForeground(new java.awt.Color(255, 255, 255));
        lblCancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCancelar.setText("CANCELAR");
        lblCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCancelarMouseClicked(evt);
            }
        });
        btnCancelar.add(lblCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 30));

        pnlBotones.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 140, 30));

        btnLimpieza.setBackground(new java.awt.Color(153, 0, 0));
        btnLimpieza.setRoundBottomLeft(20);
        btnLimpieza.setRoundBottomRight(20);
        btnLimpieza.setRoundTopLeft(20);
        btnLimpieza.setRoundTopRight(20);
        btnLimpieza.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLimpieza.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        lblLimpieza.setForeground(new java.awt.Color(255, 255, 255));
        lblLimpieza.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLimpieza.setText("LIMPIAR CADUCADOS");
        lblLimpieza.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLimpieza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLimpiezaMouseClicked(evt);
            }
        });
        btnLimpieza.add(lblLimpieza, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 30));

        pnlBotones.add(btnLimpieza, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 290, 30));

        add(pnlBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 380, 100));

        scrlPaneAlimentos.setBackground(new java.awt.Color(255, 255, 255));
        scrlPaneAlimentos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        tblAlimentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblAlimentos.setDefaultEditor(Object.class, null);
        tblAlimentos.getTableHeader().setReorderingAllowed(false);
        tblAlimentos.setRowHeight(25);
        tblAlimentos.setShowGrid(true);
        tblAlimentos.setGridColor(java.awt.Color.LIGHT_GRAY);
        tblAlimentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAlimentosMouseClicked(evt);
            }
        });
        scrlPaneAlimentos.setViewportView(tblAlimentos);

        add(scrlPaneAlimentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, -1, 450));

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });
        add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 12, 455, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        buscarAlimentos();
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void tblAlimentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAlimentosMouseClicked
        cargarDatos();
    }//GEN-LAST:event_tblAlimentosMouseClicked

    private void lblDonarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDonarMouseClicked
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        DlgBuscarPersonas dlg = new DlgBuscarPersonas(frame, true);
        dlg.setLocationRelativeTo(this);
        dlg.setVisible(true);

    }//GEN-LAST:event_lblDonarMouseClicked

    private void lblCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancelarMouseClicked
        limpiarCampos();
    }//GEN-LAST:event_lblCancelarMouseClicked

    private void lblLimpiezaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLimpiezaMouseClicked
        eliminarCaducados();
    }//GEN-LAST:event_lblLimpiezaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.donacionAlimentos.view.components.PanelRound btnCancelar;
    private com.donacionAlimentos.view.components.PanelRound btnDonar;
    private com.donacionAlimentos.view.components.PanelRound btnLimpieza;
    private javax.swing.JLabel lblCancelar;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblDonar;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblLimpieza;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTituloDP;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlCantidad;
    private com.donacionAlimentos.view.components.PanelRound pnlDatosPersonales;
    private javax.swing.JPanel pnlId;
    private javax.swing.JPanel pnlNombre;
    private javax.swing.JPanel pnlTipo;
    private javax.swing.JScrollPane scrlPaneAlimentos;
    private javax.swing.JTable tblAlimentos;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables

    /**
     * metodo interno para cargar datos en la tabla
     */
    private void cargarAlimentos() {
        tblAlimentos.setModel(almController.obtenerTablaAlimentos());
    }

    /**
     * metodo interno que usa el controlador para guardar alimentos
     */
    private void registrarDonacion() {
    }

    /**
     * metodo interno de utilidad
     */
    private void limpiarCampos() {
        txtId.setText("0");
        txtNombre.setText("");
        txtCantidad.setText("");
        txtTipo.setText("");
        lblDonar.setText("GUARDAR");
        btnLimpieza.setVisible(false);
    }

    /**
     * metodo de utileria
     */
    private void cargarDatos() {
        int fila = tblAlimentos.getSelectedRow();
        if (fila >= 0) {
            txtId.setText(tblAlimentos.getValueAt(fila, 0).toString());
            txtNombre.setText(tblAlimentos.getValueAt(fila, 1).toString());
            txtCantidad.setText(tblAlimentos.getValueAt(fila, 2).toString());
            txtTipo.setText(tblAlimentos.getValueAt(fila, 3).toString());
            lblDonar.setText("ACTUALIZAR");
            btnLimpieza.setVisible(true);
        }
    }

    /**
     * metodo que usa el controlador para eliminar un alimento
     */
    private void eliminarCaducados() {
    }

    /**
     * metodo para usar el filtro modal
     */
    private void buscarAlimentos() {
        String nombre = txtBuscar.getText().trim();
        if (nombre.isEmpty()) {
            cargarAlimentos();
        } else {
            //tblAlimentos.setModel(prsController.obtenerTablaPersonasPorFiltro(nombre));
        }
    }
}
