/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.donacionAlimentos.view;

/**
 *
 * @author angel
 */
public class pnlInicio extends javax.swing.JPanel {

    /**
     * Creates new form pnlInicio
     */
    public pnlInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        imgMenu = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(860, 550));
        setPreferredSize(new java.awt.Dimension(860, 550));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0, 100));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 550));

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Donde sobra la indiferencia, falta la humanidad.");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 600, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Donde falta el pan, sobra el dolor");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 440, -1));

        imgMenu.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        imgMenu.setForeground(new java.awt.Color(255, 255, 255));
        imgMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/showcase_bl.jpg"))); // NOI18N
        imgMenu.setFocusable(false);
        add(imgMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
