
package com.donacionAlimentos.view;

import com.donacionAlimentos.controllers.PersonaController;
import com.donacionAlimentos.view.components.PLabelButton;

/**
 * clase tipo panel que permite gestionar visualmente a los donadores
 * @author erwbyel
 */
public class pnlPersonas extends javax.swing.JPanel {

    private PersonaController prsController;
    
    /**
     * Creates new form pnlDonantes
     */
    public pnlPersonas() {
        initComponents();
        prsController = new PersonaController();
        cargarPersonas();
        btnEliminar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDatosPersonales = new com.donacionAlimentos.view.components.PanelRound();
        lblTituloDP = new javax.swing.JLabel();
        pnlId = new javax.swing.JPanel();
        txtId = new javax.swing.JTextField();
        lblId = new javax.swing.JLabel();
        pnlNombre = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        pnlApPaterno = new javax.swing.JPanel();
        txtApPaterno = new javax.swing.JTextField();
        lblApPaterno = new javax.swing.JLabel();
        pnlApMaterno = new javax.swing.JPanel();
        txtApMaterno = new javax.swing.JTextField();
        lblApMaterno = new javax.swing.JLabel();
        pnlTelefono = new javax.swing.JPanel();
        txtTelefono = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        pnlCorreo = new javax.swing.JPanel();
        txtCorreo = new javax.swing.JTextField();
        lblCorreo = new javax.swing.JLabel();
        btnGuardar = new com.donacionAlimentos.view.components.PanelRound();
        lblGuardar = new PLabelButton();
        btnCancelar = new com.donacionAlimentos.view.components.PanelRound();
        lblCancelar = new PLabelButton();
        btnEliminar = new com.donacionAlimentos.view.components.PanelRound();
        lblEliminar = new PLabelButton();
        scrlPanePersonas = new javax.swing.JScrollPane();
        tblPersonas = new javax.swing.JTable();
        txtBuscar = new javax.swing.JTextField();

        setBackground(new java.awt.Color(37, 37, 64));
        setPreferredSize(new java.awt.Dimension(860, 441));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlDatosPersonales.setBackground(new java.awt.Color(23, 17, 55));
        pnlDatosPersonales.setRoundBottomRight(30);
        pnlDatosPersonales.setRoundTopRight(30);
        pnlDatosPersonales.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloDP.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        lblTituloDP.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloDP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloDP.setText("Informacion Personal");
        pnlDatosPersonales.add(lblTituloDP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 360, -1));

        pnlId.setOpaque(false);
        pnlId.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtId.setEditable(false);
        txtId.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        txtId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtId.setBorder(null);
        txtId.setFocusable(false);
        pnlId.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 5, 40, 30));

        lblId.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        lblId.setForeground(new java.awt.Color(255, 255, 255));
        lblId.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblId.setText("ID");
        pnlId.add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        pnlDatosPersonales.add(pnlId, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 300, 40));

        pnlNombre.setOpaque(false);
        pnlNombre.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombre.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        txtNombre.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNombre.setBorder(null);
        pnlNombre.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 5, 200, 30));

        lblNombre.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNombre.setText("Nombre(s)");
        pnlNombre.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 40));

        pnlDatosPersonales.add(pnlNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 300, 40));

        pnlApPaterno.setOpaque(false);
        pnlApPaterno.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtApPaterno.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        txtApPaterno.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtApPaterno.setBorder(null);
        pnlApPaterno.add(txtApPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 5, 170, 30));

        lblApPaterno.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        lblApPaterno.setForeground(new java.awt.Color(255, 255, 255));
        lblApPaterno.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblApPaterno.setText("Apellido Paterno");
        pnlApPaterno.add(lblApPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 40));

        pnlDatosPersonales.add(pnlApPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 300, 40));

        pnlApMaterno.setOpaque(false);
        pnlApMaterno.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtApMaterno.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        txtApMaterno.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtApMaterno.setBorder(null);
        pnlApMaterno.add(txtApMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 5, 170, 30));

        lblApMaterno.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        lblApMaterno.setForeground(new java.awt.Color(255, 255, 255));
        lblApMaterno.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblApMaterno.setText("Apellido Materno");
        pnlApMaterno.add(lblApMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 40));

        pnlDatosPersonales.add(pnlApMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 300, 40));

        pnlTelefono.setOpaque(false);
        pnlTelefono.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTelefono.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        txtTelefono.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTelefono.setBorder(null);
        pnlTelefono.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 5, 200, 30));

        lblTelefono.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        lblTelefono.setForeground(new java.awt.Color(255, 255, 255));
        lblTelefono.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTelefono.setText("Telefono");
        pnlTelefono.add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 40));

        pnlDatosPersonales.add(pnlTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 300, 40));

        pnlCorreo.setOpaque(false);
        pnlCorreo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCorreo.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        txtCorreo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtCorreo.setBorder(null);
        pnlCorreo.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 5, 200, 30));

        lblCorreo.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(255, 255, 255));
        lblCorreo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCorreo.setText("Correo");
        pnlCorreo.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 40));

        pnlDatosPersonales.add(pnlCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 300, 40));

        add(pnlDatosPersonales, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 370, 280));

        btnGuardar.setBackground(new java.awt.Color(0, 102, 0));
        btnGuardar.setRoundBottomLeft(20);
        btnGuardar.setRoundBottomRight(20);
        btnGuardar.setRoundTopLeft(20);
        btnGuardar.setRoundTopRight(20);
        btnGuardar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblGuardar.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        lblGuardar.setForeground(new java.awt.Color(255, 255, 255));
        lblGuardar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGuardar.setText("GUARDAR");
        lblGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.add(lblGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 30));

        add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 140, 30));

        btnCancelar.setBackground(new java.awt.Color(0, 51, 153));
        btnCancelar.setRoundBottomLeft(20);
        btnCancelar.setRoundBottomRight(20);
        btnCancelar.setRoundTopLeft(20);
        btnCancelar.setRoundTopRight(20);
        btnCancelar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCancelar.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        lblCancelar.setForeground(new java.awt.Color(255, 255, 255));
        lblCancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCancelar.setText("CANCELAR");
        lblCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.add(lblCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 30));

        add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 140, 30));

        btnEliminar.setBackground(new java.awt.Color(153, 0, 0));
        btnEliminar.setRoundBottomLeft(20);
        btnEliminar.setRoundBottomRight(20);
        btnEliminar.setRoundTopLeft(20);
        btnEliminar.setRoundTopRight(20);
        btnEliminar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEliminar.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        lblEliminar.setForeground(new java.awt.Color(255, 255, 255));
        lblEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEliminar.setText("ELIMINAR");
        lblEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.add(lblEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 30));

        add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 290, 30));

        scrlPanePersonas.setBackground(new java.awt.Color(255, 255, 255));
        scrlPanePersonas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        tblPersonas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        scrlPanePersonas.setViewportView(tblPersonas);

        add(scrlPanePersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, -1, 450));

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });
        add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 12, 455, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        //buscar();
    }//GEN-LAST:event_txtBuscarKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.donacionAlimentos.view.components.PanelRound btnCancelar;
    private com.donacionAlimentos.view.components.PanelRound btnEliminar;
    private com.donacionAlimentos.view.components.PanelRound btnGuardar;
    private javax.swing.JLabel lblApMaterno;
    private javax.swing.JLabel lblApPaterno;
    private javax.swing.JLabel lblCancelar;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblEliminar;
    private javax.swing.JLabel lblGuardar;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTituloDP;
    private javax.swing.JPanel pnlApMaterno;
    private javax.swing.JPanel pnlApPaterno;
    private javax.swing.JPanel pnlCorreo;
    private com.donacionAlimentos.view.components.PanelRound pnlDatosPersonales;
    private javax.swing.JPanel pnlId;
    private javax.swing.JPanel pnlNombre;
    private javax.swing.JPanel pnlTelefono;
    private javax.swing.JScrollPane scrlPanePersonas;
    private javax.swing.JTable tblPersonas;
    private javax.swing.JTextField txtApMaterno;
    private javax.swing.JTextField txtApPaterno;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

    private void cargarPersonas(){
        tblPersonas.setModel(prsController.obtenerTablaClientes());
    }

}
